### ISSUE TITLE
How to run this code

### ISSUE THREAD

**Issue by chenwenfang** [jpalowitch/CCME_analyses#1]
Is there a readme.txt for me to know how this code work?
thanks!

**Comment by jpalowitch** [comment]
Hi, sorry for the very late reply. I've now added a README which should help. Thanks for the question!

**Comment by chenwenfang** [comment]
Thank you for your reply. It helped me a lot.




------------------ 原始邮件 ------------------
发件人: "jpalowitch"<notifications@github.com>; 
发送时间: 2019年5月31日(星期五) 下午3:12
收件人: "jpalowitch/CCME_analyses"<CCME_analyses@noreply.github.com>; 
抄送: "陈文方--大连理工大学"<2293508387@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [jpalowitch/CCME_analyses] How to run this code (#1)




Hi, sorry for the very late reply. I've now added a README which should help. Thanks for the question!
